version: '3'

services:

  ### JENKINS Server Container ###

  jenkins:
    build: ./jenkins
    volumes:
      - ./jenkins/lib/jenkins:/var/lib/jenkins
      - /var/run/docker.sock:/var/run/docker.sock
      - ./nginx/www:/var/www:cached
    ports:
      - "${JENKINS_PORT}:8080"
    networks:
      - backend

  ### NGINX Server Container ####

  nginx:
    build: ./nginx
    volumes:
      - ./nginx/logs/:/var/log/nginx
      - ./nginx/sites:/etc/nginx/sites-available
      - ./nginx/h5bp:/etc/nginx/h5bp
      - ./nginx/www:/var/www
    ports:
      - "${NGINX_HOST_HTTP_PORT}:80"
      - "${NGINX_HOST_HTTPS_PORT}:443"
    networks:
      - backend

networks:
  backend:
    driver: "bridge"