version: '2'

services:
  jenkins:
    build: ./jenkins
    volumes:
      - ./jenkins/lib/jenkins:/var/lib/jenkins
      - /var/run/docker.sock:/var/run/docker.sock
      - $HOME/.ssh:~/.ssh
    ports:
      - "${JENKINS_PORT}:8080"
    networks:
      - backend      
      
networks:
  backend:
    driver: "bridge"