version: '2'

services:
  jenkins:
    build: ./jenkins
    volumes:
      - ${DATA_SAVE_PATH}/jenkins:/var/lib/jenkins
      - /var/run/docker.sock:/var/run/docker.sock
      - $HOME/.ssh:/var/jenkins_home/.ssh
    ports:
      - "${JENKINS_PORT}:8080"
    networks:
      - backend      
      
networks:
  backend:
    driver: "bridge"